import { ratingOptions, type Rating } from "./SectionA";

export type SectionBAnswers = Record<string, Rating>;
const sectionBQuestions = [
  "¿El empleado llega atrasado al momento de irse a su lugar de trabajo?", "¿El empleado olvida su equipo de trabajo al momento de presentarse?", "¿El empleado llega preparado a su trabajo según las condiciones meteorológicas?", "¿El empleado parece motivado para su día de trabajo?", "¿El empleado muestra una actitud positiva hacia sus colegas?", "¿El empleado muestra una actitud positiva hacia su supervisor?", "¿El empleado muestra una actitud positiva hacia la empresa?", "¿El empleado muestra un aumento de su rendimiento?", "¿El empleado muestra desaprobación al cambiar de tipo de trabajo?", "¿El empleado ayuda a sus compañeros en dificultades?", "¿El empleado es voluntario para realizar tareas adicionales?", "¿El empleado está dispuesto a trabajar horas adicionales?", "¿El empleado se queja de sus compañeros?", "¿El empleado se queja de su supervisor?", "¿El empleado se queja del trabajo que realiza?", "¿El empleado se queja de la empresa?", "¿El empleado incita a los demás a trabajar más lento?", "¿El empleado motiva a sus compañeros de trabajo?", "¿El empleado escucha y cumple las instrucciones de su supervisor?", "¿El empleado mantiene los campos limpios?", "¿El empleado mantiene los vehículos limpios?", "¿El empleado tiene una buena actitud?", "¿El empleado evita tomar riesgos inútiles?", "¿El empleado respeta las reglas de salubridad?", "¿El empleado respeta las reglas y políticas de la finca?", "¿El empleado brinda un trabajo de calidad?", "¿El empleado cuida su material de trabajo?", "¿El empleado bromea con sus compañeros de trabajo?", "¿El empleado tiene propósitos inadecuados en el lugar de trabajo?", "¿El empleado sigue el ritmo de los demás?", "¿El empleado muestra un rendimiento constante?", "¿El empleado muestra voluntad de aprender?", "¿El empleado puede realizar su trabajo de manera independiente?", "¿El empleado necesita ser vigilado?", "¿El empleado permite al grupo alcanzar sus objetivos?", "¿El empleado valora su trabajo?", "¿Estoy feliz de tener al empleado en mi grupo?",
].map((question, index) => ({ id: `question_${index + 1}`, question, campoOnly: [2, 3, 15, 20, 21, 28, 29].includes(index + 1) }));

type Props = { answers: SectionBAnswers; workType: "bodega" | "campo"; onChange: (answers: SectionBAnswers) => void; onBack: () => void; onNext: () => void };
export default function SectionB({ answers, workType, onChange, onBack, onNext }: Props) {
  const questions = sectionBQuestions.filter((question) => !question.campoOnly || workType === "campo");
  return <>
    <div className="border-b border-primary/30 pb-3"><p className="text-xs font-bold uppercase tracking-widest text-secondary">Sección B</p><h4 className="mt-1 text-xl font-semibold text-slate-950">Preguntas</h4><p className="mt-1 text-sm text-slate-600">Seleccione una valoración para cada pregunta.</p></div>
    <div className="mt-4 space-y-3">{questions.map((question, index) => <fieldset key={question.id} className="rounded-xl border border-slate-200 p-4"><legend className="sr-only">Pregunta {index + 1}</legend><p className="text-sm font-medium leading-6 text-slate-800"><span className="mr-1 font-bold text-secondary">{index + 1}.</span>{question.question}</p><div className="mt-3 grid gap-2 sm:grid-cols-3">{ratingOptions.map((option) => <label key={option.value} className={`rating-option ${answers[question.id] === option.value ? "rating-option-selected" : ""}`}><input type="radio" name={`section-b-${question.id}`} checked={answers[question.id] === option.value} onChange={() => onChange({ ...answers, [question.id]: option.value })} className="size-4 accent-secondary" />{option.label}</label>)}</div></fieldset>)}</div>
    <div className="mt-5 flex items-center justify-between gap-3"><button type="button" onClick={onBack} className="button-secondary">Anterior</button><button type="button" onClick={onNext} className="button-primary">Siguiente</button></div>
  </>;
}
